### ISSUE TITLE
Does not build on Windows 10

### ISSUE THREAD

**Issue by smcmahon** [plone/plone.staticresources#35]
Attempting to install on Windows 10 results in a sandbox violation from EasyInstall:

```
error: Setup script exited with error: SandboxViolation: open('build\\bdist.win-amd64\\egg\\plone\\staticresources\\static\\components\\cs-jqtree-contextmenu\\node_modules\\jqtree\\static\\bower_components\\bootstrap\\dist\\fonts\\glyphicons-halflings-regular.eot', 'wb') {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.

An error occurred when trying to install c:\users\steve\plone\buildout-cache\downloads\dist\plone.staticresources-1.1.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing instance.
  Getting distribution for 'plone.staticresources==1.1.0'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "c:\users\steve\plone\python-2.7\lib\site-packages\zc\buildout\buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "c:\users\steve\plone\python-2.7\lib\site-packages\zc\buildout\buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "c:\users\steve\plone\python-2.7\lib\site-packages\zc\buildout\buildout.py", line 1603, in _call
    return f()
  File "c:\users\steve\plone\buildout-cache\eggs\plone.recipe.zope2instance-6.3.0-py2.7.egg\plone\recipe\zope2instance\recipe.py", line 145, in install
    installed.extend(self.install_scripts())
  File "c:\users\steve\plone\buildout-cache\eggs\plone.recipe.zope2instance-6.3.0-py2.7.egg\plone\recipe\zope2instance\recipe.py", line 782, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "c:\users\steve\plone\buildout-cache\eggs\zc.recipe.egg-2.0.7-py2.7.egg\zc\recipe\egg\egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "c:\users\steve\plone\buildout-cache\eggs\zc.recipe.egg-2.0.7-py2.7.egg\zc\recipe\egg\egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "c:\users\steve\plone\python-2.7\lib\site-packages\zc\buildout\easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "c:\users\steve\plone\python-2.7\lib\site-packages\zc\buildout\easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "c:\users\steve\plone\python-2.7\lib\site-packages\zc\buildout\easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "c:\users\steve\plone\python-2.7\lib\site-packages\zc\buildout\easy_install.py", line 1740, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: need more than 0 values to unpack
```

**Comment by ewohnlich** [comment]
I'm hitting a similar issue when trying to setup 5.2 on windows. I normally try to do a minimal buildout installation rather than use the unified installer but it does look like the root problem is related to plone.staticresources regardless. For what it's worth I get a slightly different failure point when trying to install with buildout vs. using pip/virtualenv. With the latter I get the same error message you posted above. With buildout it fails trying to access a fontawesome resource.

```
(venv) C:\Plone52>buildout
Uninstalling _mr.developer.
Unused options for buildout: 'old-eggs-directory'.
Installing _mr.developer.
Generated script 'C:\\Plone52\\bin\\develop'.
Installing plone.
Getting distribution for 'plone.staticresources==1.1.0'.
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*' found under directory 'news'
warning: no previously-included files found matching 'news'
error: Setup script exited with error: could not create 'build\lib\plone\staticresources\static\components\cs-jqtree-contextmenu\node_modules\jqtree\static\bower_components\fontawesome\web-fonts-with-css\css\fontawesome-all.min.css': No such file or directory
An error occurred when trying to install C:\Users\wohnlice\AppData\Local\Temp\tmpcr2kquf9get_dist\plone.staticresources-1.1.0.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing plone.
  Getting distribution for 'plone.staticresources==1.1.0'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "C:\Plone52\venv\lib\site-packages\zc\buildout\buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "C:\Plone52\venv\lib\site-packages\zc\buildout\buildout.py", line 817, in install
    installed_files = self[part]._call(recipe.install)
  File "C:\Plone52\venv\lib\site-packages\zc\buildout\buildout.py", line 1603, in _call
    return f()
  File "c:\plone52\eggs\plone.recipe.zope2instance-6.3.0-py3.6.egg\plone\recipe\zope2instance\recipe.py", line 145, in install
    installed.extend(self.install_scripts())
  File "c:\plone52\eggs\plone.recipe.zope2instance-6.3.0-py3.6.egg\plone\recipe\zope2instance\recipe.py", line 782, in install_scripts
    requirements, ws = self.egg.working_set(['plone.recipe.zope2instance'])
  File "c:\plone52\eggs\zc.recipe.egg-2.0.7-py3.6.egg\zc\recipe\egg\egg.py", line 87, in working_set
    allow_unknown_extras=bool_option(buildout_section, 'allow-unknown-extras')
  File "c:\plone52\eggs\zc.recipe.egg-2.0.7-py3.6.egg\zc\recipe\egg\egg.py", line 168, in _working_set
    allow_unknown_extras=allow_unknown_extras)
  File "C:\Plone52\venv\lib\site-packages\zc\buildout\easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "C:\Plone52\venv\lib\site-packages\zc\buildout\easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "C:\Plone52\venv\lib\site-packages\zc\buildout\easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "C:\Plone52\venv\lib\site-packages\zc\buildout\easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)

```
zc.buildout 2.13.2
setuptools 41.0.1
pip 19.2.1
buildout.cfg extends http://dist.plone.org/release/5.2/versions.cfg

Not sure if the use of the user AppData directory is a hint
