### ISSUE TITLE
./bin/plone-compile-resources raises an exception

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.staticresources#4]
After fixing #2 (PR coming) ./bin/plone-compile-resources does not exit succesfully:
```
[ale@emily plone.staticresources]$ ./bin/plone-compile-resources 
Setup npm env
Running command: npm install
...
Running command: /home/ale/Code/plone/packages/plone.staticresources/bin/instance run /home/ale/Code/plone/packages/plone.staticresources/src/plone/staticresources/_scripts/_generate_gruntfile.py
Traceback (most recent call last):
  File "/home/ale/Code/plone/packages/plone.staticresources/bin/instance", line 251, in <module>
    + sys.argv[1:]))
  File "/home/ale/Code/plone/packages/plone.staticresources/devsrc/plone.recipe.zope2instance/src/plone/recipe/zope2instance/ctl.py", line 869, in main
    options = ZServerCtlOptions()
NameError: name 'ZServerCtlOptions' is not defined
Traceback (most recent call last):
  File "./bin/plone-compile-resources", line 247, in <module>
    sys.exit(plone.staticresources._scripts.compile_resources.main())
  File "/home/ale/Code/plone/packages/plone.staticresources/src/plone/staticresources/_scripts/compile_resources.py", line 154, in main
    args.compile_dir
  File "/home/ale/Code/plone/packages/plone.staticresources/src/plone/staticresources/_scripts/compile_resources.py", line 56, in generate_gruntfile
    subprocess.check_call(cmd, env=os.environ)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/ale/Code/plone/packages/plone.staticresources/bin/instance', 'run', '/home/ale/Code/plone/packages/plone.staticresources/src/plone/staticresources/_scripts/_generate_gruntfile.py']' returned non-zero exit status 1.
```

**Comment by ale-rt** [comment]
Not an issue anymore
